branches:
  only:
  - master
language: generic
sudo: true
dist: bionic
cache:
  directories:
  - /home/travis/.vagrant.d/boxes
  - /var/lib/libvirt/images
before_install:
 - ./pre-build.sh
 - unset GEM_PATH GEM_HOME
script: travis_wait 50 ./build.sh
after_success: ./post-build.sh
