env:
  global:
    - TAILS_ORIGIN=https://git-tails.immerda.ch/tails
    - TAILS_VERSION=stable
    # see https://tails.boum.org/contribute/build
    - TAILS_BUILD_OPTIONS= 
    - ARTIFACTS=".."

branches:
  only:
  - master

os: linux
dist: bionic
language: generic

cache:
  directories:
  - /home/travis/.vagrant.d/boxes
  - /home/travis/.images

# Travis limit run time to 50 min
# As it may be too short, we define 3 stages
jobs:
  include:
    # Setup env. Cache Vagrant box. Dont try to build.
    - stage: stage1
      name: "Setup Env."
      script: skip
    # Try 1, likely to be too short but will feed apt-cache-ng
    - stage: stage2
      name: "First attempt."
    # Try 2, travis shall succedded. TODO, only run if necessary (cache)
    - stage: stage3
      name: "Second attempt."
   allow_failures:
      - stage: stage2


addons:
  apt:
    # https://tails.boum.org/contribute/build
    update: true
    packages:
     - psmisc
     - git
     - rake
     - libvirt-daemon-system
     - dnsmasq-base
     - ebtables
     - qemu-system-x86
     - qemu-utils
     - vagrant
     - vagrant-libvirt
     - vmdebootstrap

before_install:
 # Remove travis overides
 - unset GEM_PATH GEM_HOME
 - sudo adduser $(whoami) kvm
 - sudo adduser $(whoami) libvirt
 - sudo adduser $(whoami) libvirt-qemu
 # vagrant ssh breaks without it. !!!FIXME report!!!
 - sudo chmod 755 $HOME
 - sudo chmod 755 $HOME/.ssh 
 - sudo chmod 755 $HOME/.ssh/config
 - sudo adduser libvirt-qemu $(id -gn)
 - sudo systemctl restart libvirtd
 # cache cant be restored as it would requires sudo ; we do it ourselves
 - sudo mv /home/travis/.images/* /var/lib/libvirt/images || true

install:
 - git clone --recurse-submodules  -j4 $TAILS_ORIGIN
 - cd tails; git checkout $TAILS_VERSION
 # We use sudo su $(whoami) to force re-read of added groups
 - sudo su $(whoami) -c "rake basebox:clean_old"
 - sudo su $(whoami) -c "rake basebox:create"
 - sudo su $(whoami) -c "rake vm:up"

script:
 # We dance to make travis happy \o/ while we output nothing
 # Note that all the next commands are in fact concatened
 - while sleep 5m; do echo 'Staying aliiiveeeee'; done &
     timeout 2700 sudo su $(whoami) -c "rake build";
   kill %1

before_cache:
 - sudo su $(whoami) -c "rake vm:destroy"
 - sudo mv /var/lib/libvirt/images/* /home/travis/.images/
 - sudo chown -R $(whoami):$(id -gn) /home/travis/.images/

after_success:
 - sha256sum $ARTIFACTS/*.img
 - sha256sum $ARTIFACTS/*.iso

