env:
  global:
    - TAILS_ORIGIN=https://git-tails.immerda.ch/tails
    - TAILS_VERSION=stable
    # see https://tails.boum.org/contribute/build
    - TAILS_BUILD_OPTIONS= 
    - ARTIFACTS=".."
    # Only build base VM
    # - INIT_CACHE_ONLY=1

branches:
  only:
  - master

os: linux
dist: bionic
language: generic

cache:
  directories:
  - /home/travis/.vagrant.d/boxes
  - /home/travis/.images

jobs:
  include:
    - name: stage1
    - stage: stage1
    - script: skip

    - name: stage2
    - stage: stage2

    - name: stage3
    - stage: stage3

addons:
  apt:
    # https://tails.boum.org/contribute/build
    update: true
    packages:
     - psmisc
     - git
     - rake
     - libvirt-daemon-system
     - dnsmasq-base
     - ebtables
     - qemu-system-x86
     - qemu-utils
     - vagrant
     - vagrant-libvirt
     - vmdebootstrap

before_install:
 # Remove travis overides
 - unset GEM_PATH GEM_HOME
 - sudo adduser $(whoami) kvm
 - sudo adduser $(whoami) libvirt
 - sudo adduser $(whoami) libvirt-qemu
 # vagrant ssh breaks without it. !!!FIXME report!!!
 - sudo chmod 755 $HOME
 - sudo chmod 755 $HOME/.ssh 
 - sudo chmod 755 $HOME/.ssh/config
 - sudo adduser libvirt-qemu $(id -gn)
 - sudo systemctl restart libvirtd
 # cache cant be restored as it would requires sudo ; we do it ourselves
 - sudo mv /home/travis/.images/* /var/lib/libvirt/images || true

install:
 - git clone --recurse-submodules  -j4 $TAILS_ORIGIN
 - cd tails; git checkout $TAILS_VERSION
 # We use sudo su $(whoami) to force re-read of added groups
 - sudo su $(whoami) -c "rake basebox:clean_old"
 - sudo su $(whoami) -c "rake basebox:create"
 - sudo su $(whoami) -c "rake vm:up"

script:
 # Dance to make travis happy \o/
 # But not for too long, we have to cache things after...
 # Note that all the next commands are in fact concatened
 - while sleep 5m; do echo 'Staying aliiiveeeee'; done &
     timeout 2700 sudo su $(whoami) -c "rake build";
   kill %1

before_cache:
 - sudo su $(whoami) -c "rake vm:destroy"
 - sudo mv /var/lib/libvirt/images/* /home/travis/.images/
 - sudo chown -R $(whoami):$(id -gn) /home/travis/.images/

after_success:
 - sha256sum $ARTIFACTS/*.img
 - sha256sum $ARTIFACTS/*.iso

