branches:
  only:
  - master

os: linux
dist: bionic
language: minimal

# Travis limits run time to 50 min
# As it may be too short, we define 3 stages
jobs:
  include:
    # Setup env & Vagrant box. Dont try to build.
    - stage: stage1
      name: "Setup Env."
      script: skip
      after_success: skip
    # Try 1, likely to be time-short but will feed cache
    - allow_failures:
      stage: stage2
      name: "First attempt."
    # Try 2, travis shall succedded. TODO, only run if necessary (cache)
    - stage: stage3
      name: "Second attempt."

# We maintain a manual cache to allow us to cache selected files
# and to restore files that would requires sudo access.
cache:
  directories:
  - /home/travis/.vagrant.d/boxes
  - $MANUAL_CACHE_DIR
  timeout: 180
env:
  global: 
    - MANUAL_CACHE_DIR: $HOME/cache
    - MANUAL_CACHE_SRC:
      - /var/lib/libvirt/images/tails-website-cache.qcow2
      - /var/lib/libvirt/images/apt-cacher-ng-data.qcow2
      # We dont cache the followings:
      # /var/lib/libvirt/images/tails-builder*.img

addons:
  apt:
    update: true
    packages:
     - psmisc
     - git
     - rake
     - libvirt-daemon-system
     - dnsmasq-base
     - ebtables
     - qemu-system-x86
     - qemu-utils
     - vagrant
     - vagrant-libvirt
     - vmdebootstrap

before_install:
 # We setup Set Environment vars ourself, as defining them in
 # Travis configuration may end using a different cache, which
 # would completely defeat its purpose.
 - export TAILS_ORIGIN=https://git-tails.immerda.ch/tails
 - export TAILS_VERSION=stable
 - export ARTIFACTS=".."
 # Use Travis internal proxy for caching. Seems to provide no gain
 # - export http_proxy=$TRAVIS_HTTP_PROXY
 # - export TAILS_BUILD_OPTIONS=vmproxy+extproxy
 # Remove travis overides
 - unset GEM_PATH GEM_HOME
 - for group in kvm libvirt libvirt-qemu; do
     sudo adduser "$(whoami)" "$group";
   done
 # vagrant ssh breaks without it. !!!FIXME report!!!
 - sudo chmod 755 $HOME
 - sudo chmod 755 $HOME/.ssh 
 - sudo chmod 755 $HOME/.ssh/config
 - sudo adduser libvirt-qemu $(id -gn)
 - sudo systemctl restart libvirtd
 # Restore our manual cache
 - test -f $CACHE_DIR/*.tar && sudo tar xf $CACHE_DIR/*.tar / || true

install:
 - git clone --recurse-submodules  -j4 $TAILS_ORIGIN
 - cd tails; git checkout $TAILS_VERSION
 # We use sudo su $(whoami) to force re-read of added groups
 - sudo su "$(whoami)" -c "rake basebox:clean_old"
 - sudo su "$(whoami)" -c "rake basebox:create"
 - sudo su "$(whoami)" -c "rake vm:up"

script:
 # We dance to make travis happy \o/ while we output nothing
 - while sleep 5m; do echo "Staying aliiiveeeee"; done &
     timeout 2700 sudo su "$(whoami)" -c "rake build";
   kill %1

before_cache:
 - for x in $MANUAL_CACHE_SRC; do
     sudo tar -cf $HOME_DIR/$(basename $x) $x;
   done
 - ls -lah $CACHE_DIR

after_success:
 - sha256sum $ARTIFACTS/*.img
 - sha256sum $ARTIFACTS/*.iso

