env:
  global:
    - INIT_CACHE_ONLY=1
    - TAILS_ORIGIN=https://git-tails.immerda.ch/tails
    - TAILS_VERSION=stable
    - TAILS_BUILD_OPTIONS=ignorechanges

branches:
  only:
  - master

os: linux
dist: bionic
language: generic

cache:
  directories:
  - /home/travis/.vagrant.d/boxes
  - /home/travis/.images

addons:
  apt:
    update: true
    # https://tails.boum.org/contribute/build
    packages:
     - psmisc
     - git
     - rake
     - libvirt-daemon-system
     - dnsmasq-base
     - ebtables
     - qemu-system-x86
     - qemu-utils
     - vagrant
     - vagrant-libvirt
     - vmdebootstrap

before_install:
 # Remove travis overides
 - unset GEM_PATH GEM_HOME
 - sudo adduser $(whoami) kvm
 - sudo adduser $(whoami) libvirt
 - sudo adduser $(whoami) libvirt-qemu
 # vagrant ssh breaks without it. !!!FIXME report!!!
 - sudo chmod 755 $HOME
 - sudo chmod 755 $HOME/.ssh 
 - sudo chmod 755 $HOME/.ssh/config;
 - sudo adduser libvirt-qemu $(id -gn)
 - sudo systemctl restart libvirtd
 # cache cant be restored as it would requires sudo ; we do it ourselves
 - sudo mv /home/travis/.images/* /var/lib/libvirt/images || true

install:
 - git clone --recurse-submodules  -j4 $TAILS_ORIGIN
 - cd tails; git checkout $TAILS_VERSION
 # Force re-read of permissions
 - sudo su $(whoami) -c "rake basebox:clean_old"
 - sudo su $(whoami) -c "rake basebox:create"
 - sudo su $(whoami) -c "rake vm:up"

script:
 - test INIT_CACHE_ONLY == 1 && exit 0
 - while sleep 9m; do echo staying aliiiveeeeee; done &
   - sudo su travis -c "rake build"
 - kill %1

before_cache:
 - sudo su travis -c "rake vm:destroy"
 - sudo mv /var/lib/libvirt/images/* /home/travis/.images/ 
 - sudo chown -R $(whoami):$(whoami) /home/travis/.images/ 

after_success:
 - sha256sum tails/tails-*

